# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58914b2abfbb25218f1d49455b869c8e4591fc8ffe0aa34dd417b12355c46a5a68e245f3083bd4419a14a938bdb7c3275b0c095fce07c9681a60136b95633476

test:
  secret_key_base: 5ec3b89bda945a470e3c8c8b11bbc18ed55c28a965a11b770d688a06188672a384302ab7060bef5d42db224de019cad7bf3ebffb10f584ccdda05e4b381ea271

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
